"""Fix migrations

Revision ID: a3895c939d17
Revises: 3356c3d1519d
Create Date: 2025-01-20 19:44:06.584056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3895c939d17'
down_revision: Union[str, None] = '3356c3d1519d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_books_order_id_fkey', 'order_books', type_='foreignkey')
    op.drop_constraint('order_books_book_id_fkey', 'order_books', type_='foreignkey')
    op.create_foreign_key(None, 'order_books', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order_books', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_books', type_='foreignkey')
    op.drop_constraint(None, 'order_books', type_='foreignkey')
    op.create_foreign_key('order_books_book_id_fkey', 'order_books', 'books', ['book_id'], ['id'])
    op.create_foreign_key('order_books_order_id_fkey', 'order_books', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
