export { default as Home } from './home/Home.tsx'
export { default as Shop } from './shop/Shop.tsx'
export { ErrorPage } from '@/pages/errorPage/ErrorPage.tsx'
export { default as Cart } from '@/pages/cart/Cart.tsx'
export { default as Book } from '@/pages/book/Book.tsx'
export { default as Checkout } from '../pages/checkout/Checkout.tsx'
